from __future__ import annotations

import importlib
import io
import os
import shutil
import subprocess
import sys
import tempfile
import wave
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.config import get_settings


class VoiceUnavailableError(RuntimeError):
    """Raised when the configured voice backend is not ready."""


class GladosVoiceService:
    def status(self) -> dict[str, str | bool]:
        """
        Return status information for the requested operation.

        Returns:
            Dictionary containing the requested data.
        """
        try:
            _get_glados_tts()
        except VoiceUnavailableError as exc:
            return {
                "available": False,
                "backend": "glados",
                "detail": str(exc),
            }

        return {
            "available": True,
            "backend": "glados",
            "detail": "GLaDOS voice is ready.",
        }

    def synthesize_wav(self, text: str) -> bytes:
        """
        Synthesize wav.

        Args:
            text: Text to synthesize or announce.

        Returns:
            Generated byte payload.

        Raises:
            VoiceUnavailableError: If the operation cannot be completed.
        """
        try:
            tts = _get_glados_tts()
            audio = tts.generate_speech_audio(text)
        except VoiceUnavailableError:
            raise
        except Exception as exc:
            raise VoiceUnavailableError(f"GLaDOS voice synthesis failed: {exc}") from exc

        settings = get_settings()
        sample_rate = int(getattr(tts, "sample_rate", settings.voice_sample_rate))
        return _audio_to_wav_bytes(audio, sample_rate)

    def announce(self, text: str) -> None:
        """
        Announce the requested operation.

        Args:
            text: Text to synthesize or announce.

        Returns:
            None.
        """
        wav_bytes = self.synthesize_wav(text)
        _play_wav_bytes(wav_bytes)


@lru_cache(maxsize=1)
def _get_glados_tts() -> Any:
    """
    Return the cached GLaDOS TTS backend instance.

    Returns:
        Any result.

    Raises:
        VoiceUnavailableError: If the operation cannot be completed.
    """
    module = _load_glados_module()
    try:
        return module.TTS()
    except AttributeError as exc:
        raise VoiceUnavailableError("GLaDOS-TTS was found, but the TTS class is missing.") from exc
    except Exception as exc:
        raise VoiceUnavailableError(f"Could not initialize GLaDOS-TTS: {exc}") from exc


def _load_glados_module() -> Any:
    """
    Load the vendored GLaDOS TTS module.

    Returns:
        Any result.

    Raises:
        VoiceUnavailableError: If the operation cannot be completed.
    """
    try:
        return importlib.import_module("glados")
    except ImportError:
        settings = get_settings()
        repo_path = Path(settings.voice_glados_repo_path).resolve()
        if not repo_path.exists():
            raise VoiceUnavailableError(
                "GLaDOS-TTS is not installed. Clone the repo into "
                f"{settings.voice_glados_repo_path} or make `glados` importable."
            ) from None

        repo_str = str(repo_path)
        if repo_str not in sys.path:
            sys.path.insert(0, repo_str)

        try:
            return importlib.import_module("glados")
        except ImportError as exc:
            raise VoiceUnavailableError(
                "Found the GLaDOS-TTS repository, but Python still could not import `glados`."
            ) from exc


def _audio_to_wav_bytes(audio: Any, sample_rate: int) -> bytes:
    """
    Convert generated audio samples into WAV bytes.

    Args:
        audio: Audio value.
        sample_rate: Audio sample rate in hertz.

    Returns:
        Generated byte payload.
    """
    samples = _coerce_samples(audio)
    pcm_frames = bytearray()

    for sample in samples:
        clipped = max(-1.0, min(1.0, float(sample)))
        pcm_value = int(clipped * 32767)
        pcm_frames.extend(pcm_value.to_bytes(2, byteorder="little", signed=True))

    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(sample_rate)
        wav_file.writeframes(bytes(pcm_frames))

    return buffer.getvalue()


def _coerce_samples(audio: Any) -> list[float]:
    """
    Convert audio data into a list of float samples.

    Args:
        audio: Audio value.

    Returns:
        List of matching records or values.
    """
    if hasattr(audio, "tolist"):
        data = audio.tolist()
    else:
        data = list(audio)

    if data and isinstance(data[0], list):
        flattened: list[float] = []
        for row in data:
            flattened.extend(float(item) for item in row)
        return flattened

    return [float(item) for item in data]


def _play_wav_bytes(wav_bytes: bytes) -> None:
    """
    Play wav bytes.

    Args:
        wav_bytes: WAV audio bytes to play.

    Returns:
        None.
    """
    if sys.platform == "win32":
        _play_wav_on_windows(wav_bytes)
        return
    _play_wav_with_tempfile(wav_bytes)


def _play_wav_on_windows(wav_bytes: bytes) -> None:
    """
    Play wav on windows.

    Args:
        wav_bytes: WAV audio bytes to play.

    Returns:
        None.

    Raises:
        VoiceUnavailableError: If the operation cannot be completed.
    """
    try:
        import winsound
    except ImportError as exc:  # pragma: no cover - windows stdlib import
        raise VoiceUnavailableError(
            "Audio playback is not available on this Windows runtime."
        ) from exc

    try:
        winsound.PlaySound(wav_bytes, winsound.SND_MEMORY)
    except RuntimeError as exc:
        raise VoiceUnavailableError(f"Audio playback failed: {exc}") from exc


def _play_wav_with_tempfile(wav_bytes: bytes) -> None:
    """
    Play wav with tempfile.

    Args:
        wav_bytes: WAV audio bytes to play.

    Returns:
        None.

    Raises:
        VoiceUnavailableError: If the operation cannot be completed.
    """
    player = _find_audio_player()
    if player is None:
        raise VoiceUnavailableError(
            "Audio playback is not available. Install `aplay`, `paplay`, or `afplay`."
        )

    temp_path: str | None = None
    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as handle:
            handle.write(wav_bytes)
            temp_path = handle.name
        subprocess.run([*player, temp_path], check=True, capture_output=True)
    except subprocess.CalledProcessError as exc:
        stderr = exc.stderr.decode("utf-8", errors="ignore").strip()
        detail = stderr or str(exc)
        raise VoiceUnavailableError(f"Audio playback failed: {detail}") from exc
    finally:
        if temp_path is not None:
            try:
                os.unlink(temp_path)
            except OSError:
                pass


def _find_audio_player() -> list[str] | None:
    """
    Find an available command-line audio player.

    Returns:
        List of matching records or values.
    """
    for command in ("aplay", "paplay", "afplay"):
        executable = shutil.which(command)
        if executable is not None:
            return [executable]
    return None
