from __future__ import annotations

from app.assistant.rules.intents import (
    extract_self_improve_goal,
    is_capability_question,
    is_health_check_request,
    is_identity_question,
    is_note_add_request,
    is_note_list_request,
    is_note_lookup_request,
    is_pull_request_request,
    is_self_improve_follow_up,
    is_self_improve_request,
    is_self_update_request,
    needs_wipe_confirmation,
    should_answer_without_tools,
    tool_matches_request,
)
from app.assistant.rules.messages import (
    is_confirmation_message,
    is_presence_confirmation,
    is_rejection_message,
    is_wipe_confirmation_prompt,
    normalize_wipe_request,
    note_content_from_message,
    note_keywords_from_message,
    wipe_confirmation_prompt,
)
from app.assistant.rules.parsing import extract_json, parse_decision
from app.assistant.rules.timers import (
    duration_args_from_message,
    is_timer_cancel_request,
    is_timer_start_request,
    is_timer_status_request,
    needs_timer_duration,
    timer_confirmation,
)
from app.assistant.rules.tools import TOOL_RULES, ToolIntentRule, tool_announcement, tool_signature

__all__ = [
    "TOOL_RULES",
    "ToolIntentRule",
    "duration_args_from_message",
    "extract_json",
    "is_confirmation_message",
    "is_capability_question",
    "is_identity_question",
    "is_health_check_request",
    "is_note_add_request",
    "is_note_list_request",
    "is_note_lookup_request",
    "is_pull_request_request",
    "is_presence_confirmation",
    "is_self_improve_follow_up",
    "is_self_improve_request",
    "is_self_update_request",
    "extract_self_improve_goal",
    "is_rejection_message",
    "is_timer_cancel_request",
    "is_timer_start_request",
    "is_timer_status_request",
    "is_wipe_confirmation_prompt",
    "needs_timer_duration",
    "needs_wipe_confirmation",
    "normalize_wipe_request",
    "note_content_from_message",
    "note_keywords_from_message",
    "parse_decision",
    "should_answer_without_tools",
    "timer_confirmation",
    "tool_announcement",
    "tool_matches_request",
    "tool_signature",
    "wipe_confirmation_prompt",
]
