from __future__ import annotations

from app.assistant.rules.intents import (
    IDENTITY_OR_CAPABILITY_TRIGGERS,
    is_capability_question,
    is_health_check_request,
    is_identity_question,
    is_internal_note_list_request,
    is_pull_request_request,
    is_system_analysis_request,
    needs_reboot_confirmation,
    needs_service_restart_confirmation,
    needs_wipe_confirmation,
    should_answer_without_tools,
    tool_matches_request,
)
from app.assistant.rules.messages import (
    confirmation_followup,
    is_confirmation_message,
    is_rejection_message,
    is_wipe_confirmation_prompt,
    normalize_wipe_request,
    wipe_confirmation_prompt,
)
from app.assistant.rules.parsing import extract_json, parse_decision
from app.assistant.rules.timers import (
    duration_args_from_message,
    is_clear_all_timers_request,
    is_stopwatch_rename_request,
    is_stopwatch_start_request,
    is_stopwatch_stop_request,
    is_timer_cancel_request,
    is_timer_rename_request,
    is_timer_start_request,
    is_timer_status_request,
    needs_timer_duration,
    rename_stopwatch_args_from_message,
    rename_timer_args_from_message,
    timer_confirmation,
)
from app.assistant.rules.tools import (
    ToolIntentRule,
    build_tool_rules,
    get_tool_rule,
    tool_announcement,
    tool_signature,
)

__all__ = [
    "ToolIntentRule",
    "build_tool_rules",
    "confirmation_followup",
    "get_tool_rule",
    "duration_args_from_message",
    "extract_json",
    "IDENTITY_OR_CAPABILITY_TRIGGERS",
    "is_confirmation_message",
    "is_capability_question",
    "is_identity_question",
    "is_health_check_request",
    "is_system_analysis_request",
    "is_internal_note_list_request",
    "is_pull_request_request",
    "is_rejection_message",
    "is_clear_all_timers_request",
    "is_stopwatch_rename_request",
    "is_stopwatch_start_request",
    "is_stopwatch_stop_request",
    "is_timer_cancel_request",
    "is_timer_rename_request",
    "is_timer_start_request",
    "is_timer_status_request",
    "is_wipe_confirmation_prompt",
    "needs_reboot_confirmation",
    "needs_service_restart_confirmation",
    "needs_timer_duration",
    "needs_wipe_confirmation",
    "normalize_wipe_request",
    "parse_decision",
    "rename_stopwatch_args_from_message",
    "rename_timer_args_from_message",
    "should_answer_without_tools",
    "timer_confirmation",
    "tool_announcement",
    "tool_matches_request",
    "tool_signature",
    "wipe_confirmation_prompt",
]
